name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.88.0  # specify the exact version you want
        override: true
        components: clippy  # optional, include only if needed

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose